Xynthesis.Web/Controllers/ReporteUsuariosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Xynthesis.Modelo;
using CrystalDecisions.CrystalReports.Engine;
using CrystalDecisions.Shared;
using CrystalDecisions.Web;
using PagedList.Mvc;
using PagedList;
using System.IO;

namespace Xynthesis.Web.Controllers
{
    public class ReporteUsuariosController : Controller
    {
        xynthesisEntities xyt = new xynthesisEntities();
        public ActionResult ListaUsuarios(string paraPaginacion, string filtro, int? page)
        {
            try
            {
                var lista = xyt.xyp_SelUsuarios().ToList();
                if (!String.IsNullOrEmpty(filtro))
                {
                    var res1 = lista.Where(s => s.Nom_Subscriber.Contains(filtro));
                }

                int pageSize = 10;
                int pageNumber = (page ?? 1);

                return View(lista.ToPagedList(pageNumber, pageSize));
            }
            catch (Exception)
            {
                throw;
            }
            
        }

        public ActionResult Reportes(string opcion)
        {
            switch (opcion)
            {
                case "pdf":

                    return (ReportePDF());

                case "excel":

                    return (ReporteEXCEL());

                case "word":

                    return (ReporteWORD());

                default:
                    return View();

            }
        }

        public ActionResult ReportePDF()
        {
            List<xyp_SelUsuarios_Result> Usuarios = new List<xyp_SelUsuarios_Result>();

            Usuarios = xyt.xyp_SelUsuarios().ToList();

            ReportDocument rd = new ReportDocument();

            rd.Load(Path.Combine(Server.MapPath("~/Reportes"), "xyp_SelUsuarios.rpt"));
            rd.SetDataSource(Usuarios);


            Response.Buffer = false;
            Response.ClearContent();
            Response.ClearHeaders();
            try
            {
                //=====================Inicio para Exportar a PDF============================================
                Stream stream = rd.ExportToStream(CrystalDecisions.Shared.ExportFormatType.PortableDocFormat);
                stream.Seek(0, SeekOrigin.Begin);
                return File(stream, "application/pdf", "ReporteUsuarios.pdf");
                //=====================Fin para Exportar a PDF===============================================

            }
            catch (Exception ex)
            {
                throw ex;
            }
        }
        public ActionResult ReporteEXCEL()
        {
            List<xyp_SelUsuarios_Result> Usuarios = new List<xyp_SelUsuarios_Result>();

            Usuarios = xyt.xyp_SelUsuarios().ToList();

            ReportDocument rd = new ReportDocument();

            rd.Load(Path.Combine(Server.MapPath("~/Reportes"), "xyp_SelUsuarios.rpt"));
            rd.SetDataSource(Usuarios);

            Response.Buffer = false;
            Response.ClearContent();
            Response.ClearHeaders();
            try
            {

                //=====================Inicio para Exportar a Excel==========================================
                Stream stream = rd.ExportToStream(CrystalDecisions.Shared.ExportFormatType.Excel);
                stream.Seek(0, SeekOrigin.Begin);
                return File(stream, "application/xls", "ReporteUsuarios.xls");
                //=====================Fin para Exportar a Excel=============================================

            }
            catch (Exception ex)
            {
                throw ex;
            }
        }
        public ActionResult ReporteWORD()
        {
            List<xyp_SelUsuarios_Result> Usuarios = new List<xyp_SelUsuarios_Result>();

            Usuarios = xyt.xyp_SelUsuarios().ToList();

            ReportDocument rd = new ReportDocument();

            rd.Load(Path.Combine(Server.MapPath("~/Reportes"), "xyp_SelUsuarios.rpt"));
            rd.SetDataSource(Usuarios);

            Response.Buffer = false;
            Response.ClearContent();
            Response.ClearHeaders();
            try
            {

                //=====================Inicio para Exportar a Word===========================================
                Stream stream = rd.ExportToStream(CrystalDecisions.Shared.ExportFormatType.WordForWindows);
                stream.Seek(0, SeekOrigin.Begin);
                return File(stream, "application/doc", "ReporteUsuarios.doc");
                //=====================Fin para Exportar a Word==============================================
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }
    }
}

Xynthesis.Web/Views/ReporteUsuarios/ListaUsuarios.cshtml
@using PagedList.Mvc;
@using PagedList;
@model PagedList.IPagedList<Xynthesis.Modelo.xyp_SelUsuarios_Result>
@*@model IEnumerable<Xynthesis.Modelo.xyp_SelUsuarios_Result>*@

<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />
<link href='https://fonts.googleapis.com/css?family=Open+Sans:400,300,600' rel='stylesheet' type='text/css'>

@{
    ViewBag.Title = "ListaUsuarios";
}
<div class="container">
    <br />
    <div class="text-center">
        <h2><strong>Reporte de Usuarios</strong></h2>
    </div>
    <br />
    <br />

    <div class="row ">
        <div class="col-md-4 pull-right">
            @using (Html.BeginForm("Reportes", "ReporteUsuarios"))
            {
                @Html.TextBox("FechaInicial", null, new { @class = "form-control hidden", @type = "date", @id = "fechini" })
                @Html.TextBox("FechaFinal", null, new { @class = "form-control hidden", @type = "date", @id = "fechfin" })
                <div class="form-group form-inline pull-right">
                    <select name="opcion" class="form-control">
                        <option value="pdf">PDF</option>
                        <option value="excel">EXCEL</option>
                        <option value="word">WORD</option>
                    </select>
                    <input type="submit" name="btnGenerarReporte" id="GenerarReporte" value="GENERAR REPORTE" class="btn btn-success" />
                </div>
            }
        </div>
    </div>

    <p>

    </p>
    <table class="table table-condensed table-responsive table-hover">
        <tr>

            <th>
                <strong>NOMBRE SUBSCRIPTOR</strong>
            </th>
            <th>
                <strong>USUARIO</strong>
            </th>
            <th>
                <strong>TIPO DE USUARIO</strong>
            </th>
            <th class="text-center">
                <strong>CONTRASEÑA</strong>
            </th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>

                <td>
                    @Html.DisplayFor(modelItem => item.Nom_Subscriber)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Nom_DomainUser)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Tip_Subscriber)
                </td>
                <td class="pull-right">
                    @Html.DisplayFor(modelItem => item.Str_Password)
                </td>
            </tr>
        }

    </table>

    <br />
    Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount
    @Html.PagedListPager(Model, page => Url.Action("ListaUsuarios", new { page, opcion = ViewBag.paraPaginacion, paraPaginacion = ViewBag.paraPaginacion }))
</div>