Xynthesis.Web/Controllers/ReporteConsumosPersonalesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Xynthesis.Modelo;
using CrystalDecisions.CrystalReports.Engine;
using CrystalDecisions.Shared;
using CrystalDecisions.Web;
using PagedList.Mvc;
using PagedList;
using System.IO;
using Xynthesis.AccesoDatos;
using Xynthesis.Utilidades;

namespace Xynthesis.Web.Controllers
{
    public class ReporteConsumosPersonalesController : Xynthesis.Web.Models.FormatoReporte
    {
        Xynthesis.Utilidades.Mensaje msg = new Mensaje();
        Utilidades.LogXynthesis log = new LogXynthesis();
        Utilidades.Constantes cons = new Constantes();
        xynthesisEntities xyt = new xynthesisEntities();
        ADReporteConsumosPersonales Consper= new ADReporteConsumosPersonales();
        public int contador;
        // GET: ReporteConsumosPersonales
        public ActionResult ConsumosPersonales(string paraPaginacion, string filtro, string extension, string FechaInicial, string FechaFinal, int? page)
        {
            if (Session["Ide_Subscriber"] == null)
            {
                return RedirectToAction("Login", "Acceso");
            }
            ViewData["usuario"] = (from t in xyt.xy_subscriber
                                   where t.Ide_Subscriber != -1
                                   orderby t.Nom_Subscriber ascending
                                   select t).ToList();
            //Inicio de lineas agregadas
            if (Session["FechaInicial"] != null)
            {
                contador++;
            }

            int valor = contador;

            if (FechaInicial == null & Session["FechaInicial"] != null & valor == 1 & page == null)
            {
                Session["FechaInicial"] = null;
                Session["FechaFinal"] = null;
                Session["usuarios"] = null;
            }

            if (FechaInicial == null & Session["FechaInicial"] != null & valor == 0 & page == null)
            {
                Session["FechaInicial"] = null;
                Session["FechaFinal"] = null;
                Session["usuarios"] = null;
            }
            if (Session["Extension"] != null)
            {
                extension = Session["Extension"].ToString();
            }
                //if (FechaInicial == null & Session["FechaInicial"] != null & valor >= 1)
                //{
                //}
                //Fin de lineas agregadas

                List<xyp_SelConsumeByExtensionAndUser_Result> lista;
            try
            {
                if (Session["FechaInicial"] != null && Session["FechaFinal"] != null)
                    lista = Consper.ObtenerConsumosPersonales(Session["FechaInicial"].ToString(), Session["FechaFinal"].ToString(), extension, Session["usuarios"].ToString()).ToList();
                else
                    lista = Consper.ObtenerConsumosPersonales( null, null,null, null).ToList();

                int pageSize = cons.MaxRegGrilla == null ? 8 : Convert.ToInt32(cons.MaxRegGrilla);
                int pageNumber = (page ?? 1);

                ViewBag.fechaini = Session["FechaInicial"];
                ViewBag.fechafin = Session["FechaFinal"];
                ViewBag.extension = Session["Extension"];

                return View(lista.ToPagedList(pageNumber, pageSize));
            }
            catch (Exception ex)
            {
                log.EscribaLog("REPORTE", "Action:ConsumosPersonales " + ex.Message, Session["Nom_DomainUser"].ToString());
                throw ex;
            }
        }

        public ActionResult ConsumosPersonales_(string extension,string FechaInicial, string FechaFinal, string[] usuarioId, int? page)
        {
            string usuario = "";
            string user;
            if (usuarioId == null)
            {
                user = "";
            }
            else
            {
                for (var i = 0; i < usuarioId.Length; i++)
                {
                    usuario += usuarioId[i].ToString() + "|";
                }
                user = usuario;
            }

            Session["usuarios"] = user;
            //user = usuario;
            //Char separador = '|';
            //String[] ides = usuario.Split(separador);

            //String[] ides = usuarioId;

            ViewData["usuario"] = (from t in xyt.xy_subscriber
                                   where t.Ide_Subscriber != -1
                                   orderby t.Nom_Subscriber ascending
                                   select t).ToList();

            try
            {
                List<xyp_SelConsumeByExtensionAndUser_Result> lista = Consper.ObtenerConsumosPersonales(FechaInicial, FechaFinal, extension, user).ToList();
                int pageSize = cons.MaxRegGrilla == null ? 8 : Convert.ToInt32(cons.MaxRegGrilla);
                int pageIndex = 1;
                int pageNumber = (page ?? 1);
                pageIndex = page.HasValue ? Convert.ToInt32(page) : 1;

                Session["FechaInicial"] = FechaInicial;
                Session["FechaFinal"] = FechaFinal;
                Session["Extension"] = extension;

                ViewBag.fechaini = Session["FechaInicial"];
                ViewBag.fechafin = Session["FechaFinal"];
                ViewBag.extension = Session["Extension"];

                return View("ConsumosPersonales", lista.ToPagedList(pageIndex, pageSize));

            }
            catch (Exception ex)
            {
                log.EscribaLog("REPORTE", "Action:ConsumosPersonales " + ex.Message, Session["Nom_DomainUser"].ToString());
                throw ex;
            }
        }

        public ActionResult Reportes(string opcion)
        {
            if (Session["FechaInicial"] == null || Session["FechaFinal"] == null)
                return View("ConsumosPersonales", new List<xyp_SelConsumeByExtensionAndUser_Result>().ToPagedList(1, 1));
            else
                return ReporteFormato(opcion, "ConsumosPersonales", "ObtenerConsumosPersonales",
                    Session["FechaInicial"].ToString(), Session["FechaFinal"].ToString(), Session["Extension"].ToString(), Session["usuarios"].ToString());
        }


    }
}

Xynthesis.Web/Views/ReporteConsumosPersonales/ConsumosPersonales.cshtml
@using PagedList.Mvc;
@using PagedList;
@model PagedList.IPagedList<Xynthesis.Modelo.xyp_SelConsumeByExtensionAndUser_Result>
<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />
<link href="~/Content/Xynthesis.css" rel="stylesheet" />
<script type="text/javascript" src="~/fonts/select/js/bootstrap-select.js"></script>
<link rel="stylesheet" href="~/fonts/select/css/bootstrap-select.min.css">
<script src="~/fonts/select/js/bootstrap-select.min.js"></script>
<script src="~/fonts/select/js/i18n/defaults-*.min.js"></script>
<link rel="stylesheet" href="~/Content/selectorfiltro.css">
@{
    ViewBag.Title = "Consumos Personales";
    var mod = (List<Xynthesis.Modelo.xy_subscriber>)ViewData["usuario"];
}


<div class="container">
    <br />
    <div class="text-center">
        <h2><strong>Consumo personal</strong></h2>
    </div>
    <br />
    <br />

    <div class="row">
        <div class="col-md-10">
            @using (Html.BeginForm("ConsumosPersonales_", "ReporteConsumosPersonales", FormMethod.Get))
            {
                <div class="form-group form-inline">
                    @Html.TextBox("extension", null, new { @class = "form-control", @type = "text", @id = "extension", @placeholder = "N° Telf", @required = true, style = "width:110px" })
                    @Html.TextBox("FechaInicial", null, new { @class = "form-control", @placeholder = "Fecha inicial", style = "width:110px" })
                    @Html.TextBox("FechaFinal", null, new { @class = "form-control", @placeholder = "Fecha final", style = "width:110px" })
                    <select class="selectpicker" multiple data-actions-box="true" data-live-search="true" data-live-search-placeholder="USUARIO" title="USUARIO" id="NomUsuario" name="usuarioId" data-size="10">
                        @foreach (var usuar in mod)
                        {
                            <option id="@usuar.Nom_Subscriber" value="@usuar.Ide_Subscriber">@usuar.Nom_Subscriber</option>
                        }
                    </select>

                    <button type="submit" name="btnEnviar" id="enviar" class="btn btn-success" title="GENERAR"><i class="fas fa-file-export"></i></button>
                    <label id="lblFechas" class="control-label">@ViewBag.fechaini  @ViewBag.fechafin</label>
                </div>

                    @*<label id="lblFechas" class="control-label">@ViewBag.fechaini A @ViewBag.fechafin</label>*@
            }
        </div>
        <div class="col-md-2 text-right">
            @using (Html.BeginForm("Reportes", "ReporteConsumosPersonales"))
            {
                <div class="form-group form-inline ">
                    <select name="opcion" class="form-control">
                        <option value="pdf">PDF</option>
                        <option value="excel">EXCEL</option>
                        <option value="word">WORD</option>
                    </select>

                    <button type="submit" name="btnGenerarReporte" id="GenerarReporte" class="btn btn-success" title="EXPORTAR"><i class="fas fa-print"></i></button>
                </div>
            }
        </div>
    </div>


    <table class="table table-condensed table-responsive table-striped table-hover">
        <tr tr style="background-color:#E1E1E1;">
            <th>
                <strong>ORIGEN</strong>
            </th>
            <th>
                <strong>COBERTURA</strong>
            </th>
            <th>
                <strong>DESTINO</strong>
            </th>
            <th>
                <strong>MINUTOS</strong>
            </th>
            <th>
                <strong>COSTO</strong>
            </th>

            <th class="text-center">
                <strong>FECHA LLAMADA</strong>
            </th>

        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Ide_NumberSource)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Nom_Coverage)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Ide_NumberTarget)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.TotalMinutos)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Vlr_Cost_Pesos)
                </td>
                <td class="text-center">
                    @Html.DisplayFor(modelItem => item.Date)
                </td>

            </tr>
        }

    </table>
    <br />
    Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount
    @Html.PagedListPager(Model, page => Url.Action("ConsumosPersonales", new { page, opcion = ViewBag.paraPaginacion, paraPaginacion = ViewBag.paraPaginacion }))

</div>


<script src="~/Scripts/NotacionDecimal.js"></script>