Xynthesis.Web/Controllers/ReporteLlamadaCampeonaDuracionController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Xynthesis.Modelo;
using CrystalDecisions.CrystalReports.Engine;
using CrystalDecisions.Shared;
using CrystalDecisions.Web;
using PagedList.Mvc;
using PagedList;
using System.IO;
using Xynthesis.AccesoDatos;
using Xynthesis.Utilidades;


namespace Xynthesis.Web.Controllers
{
    public class ReporteLlamadaCampeonaDuracionController : Xynthesis.Web.Models.FormatoReporte
    {

        Xynthesis.Utilidades.Mensaje msg = new Mensaje();
        Utilidades.LogXynthesis log = new LogXynthesis();
        Utilidades.Constantes cons = new Constantes();
        ADLlamadaCampeonaDuracion llamadaCam = new ADLlamadaCampeonaDuracion();
        xynthesisEntities xyt = new xynthesisEntities();
        public int contador;

        // GET: ReporteLlamadaCampeonaDuracion
        public ActionResult LlamadaCampeonaDuracion(string paraPaginacion, string filtro, string FechaInicial, string FechaFinal, int? page)
        {
            int anioActual = DateTime.Now.Year - 1;
            DateTime Hoy = DateTime.Today;
            string fecha_actual = Hoy.ToString("yyyy-MM-dd");

            if (Session["Ide_Subscriber"] == null)
            {
                return RedirectToAction("Login", "Acceso");
            }
            ViewData["area"] = (from t in xyt.xy_costcenters select t).ToList();
            ViewData["llamadaentrante"] = (from row in xyt.xyp_SelDetailChampCallDuration(Convert.ToString(anioActual) + "-01-01", fecha_actual, "", "")
                                           orderby row.target ascending
                                           select row).Distinct().ToList();
            //Inicio de lineas agregadas
            if (Session["FechaInicial"] != null)
            {
                contador++;
            }

            int valor = contador;

            if (FechaInicial == null & Session["FechaInicial"] != null & valor == 1 & page == null)
            {
                Session["FechaInicial"] = null;
                Session["FechaFinal"] = null;
                Session["area"] = null;
                Session["llamadaentrante"] = null;
            }

            if (FechaInicial == null & Session["FechaInicial"] != null & valor == 0 & page == null)
            {
                Session["FechaInicial"] = null;
                Session["FechaFinal"] = null;
                Session["area"] = null;
                Session["llamadaentrante"] = null;
            }

            
            List<xyp_SelDetailChampCallDuration_Result> lista;
            try
            {
                if (Session["FechaInicial"] != null && Session["FechaFinal"] != null)
                    lista = llamadaCam.ObtenerLlamadaCampeonaDuracion(Session["FechaInicial"].ToString(), Session["FechaFinal"].ToString(), Session["area"].ToString(), Session["llamadaentrante"].ToString()).ToList();
                else
                    lista = llamadaCam.ObtenerLlamadaCampeonaDuracion("", "", "","").ToList();

                int pageSize = cons.MaxRegGrilla == null ? 8 : Convert.ToInt32(cons.MaxRegGrilla);
                int pageNumber = (page ?? 1);

                ViewBag.fechaini = Session["FechaInicial"];
                ViewBag.fechafin = Session["FechaFinal"];

                return View(lista.ToPagedList(pageNumber, pageSize));
            }
            catch (Exception ex)
            {
                log.EscribaLog("REPORTE", "Action:LlamadaCampeonaDuracion " + ex.Message, Session["Nom_DomainUser"].ToString());
                throw ex;
            }
        }

        public ActionResult LlamadaCampeonaDuracion_(string FechaInicial, string FechaFinal, string[] areaId, string[] numentrante, int? page)
        {
            //=====================fecha actual=============================
            int anioActual = DateTime.Now.Year - 1;
            DateTime Hoy = DateTime.Today;
            string fecha_actual = Hoy.ToString("yyyy-MM-dd");
            //=====================fecha actual=============================

            string area = "";
            string ar;
            if (areaId == null)
            {
                ar = "";
            }
            else
            {
                for (var i = 0; i < areaId.Length; i++)
                {
                    area += areaId[i].ToString() + "|";
                }
                ar = area;
            }

            Session["area"] = ar;


            //=====================Procesar llamada entrante=============================
            string llamadEntr = "";
            string llamEnt;
            if (numentrante == null)
            {
                llamEnt = "";
            }
            else
            {
                for (var i = 0; i < numentrante.Length; i++)
                {
                    llamadEntr += numentrante[i].ToString() + "|";
                }
                llamEnt = llamadEntr;
            }

            Session["llamadaentrante"] = llamEnt;
            //=====================Procesar llamada entrante=============================


            //user = usuario;
            //Char separador = '|';
            //String[] ides = usuario.Split(separador);

            //String[] ides = usuarioId;

            ViewData["area"] = (from t in xyt.xy_costcenters select t).ToList();
            ViewData["llamadaentrante"] = (from row in xyt.xyp_SelDetailChampCallDuration(Convert.ToString(anioActual) + "-01-01", fecha_actual, "", "")
                                           orderby row.target ascending
                                           select row).Distinct().ToList();

            try
            {
                List<xyp_SelDetailChampCallDuration_Result> lista = llamadaCam.ObtenerLlamadaCampeonaDuracion(FechaInicial, FechaFinal, ar, llamEnt).ToList();
                int pageSize = cons.MaxRegGrilla == null ? 8 : Convert.ToInt32(cons.MaxRegGrilla);
                int pageIndex = 1;
                int pageNumber = (page ?? 1);
                pageIndex = page.HasValue ? Convert.ToInt32(page) : 1;

                Session["FechaInicial"] = FechaInicial;
                Session["FechaFinal"] = FechaFinal;

                ViewBag.fechaini = Session["FechaInicial"];
                ViewBag.fechafin = Session["FechaFinal"];

                return View("LlamadaCampeonaDuracion", lista.ToPagedList(pageIndex, pageSize));

            }
            catch (Exception ex)
            {
                log.EscribaLog("REPORTE", "Action:LlamadaCampeonaDuracion_ " + ex.Message, Session["Nom_DomainUser"].ToString());
                throw ex;
            }
        }

        public ActionResult Reportes(string opcion)
        {
            if (Session["FechaInicial"] == null || Session["FechaFinal"] == null)
                return View("LlamadaCampeonaDuracion", new List<xyp_SelDetailChampCallDuration_Result>().ToPagedList(1, 1));
            else
                return ReporteFormato(opcion, "LlamadaCampeonaXDuracion", "ObtenerLlamadaCampeonaDuracion",
                    Session["FechaInicial"].ToString(), Session["FechaFinal"].ToString(), Session["area"].ToString(), Session["llamadaentrante"].ToString());

        }


    }
}   

Xynthesis.Web/Views/ReporteLlamadaCampeonaDuracion/LlamadaCampeonaDuracion.cshtml
@using PagedList.Mvc;
@using PagedList;
@model PagedList.IPagedList<Xynthesis.Modelo.xyp_SelDetailChampCallDuration_Result>
<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />
<link href="~/Content/Xynthesis.css" rel="stylesheet" />

<script type="text/javascript" src="~/fonts/select/js/bootstrap-select.js"></script>
<link rel="stylesheet" href="~/fonts/select/css/bootstrap-select.min.css">
<script src="~/fonts/select/js/bootstrap-select.min.js"></script>
<script src="~/fonts/select/js/i18n/defaults-*.min.js"></script>
<link rel="stylesheet" href="~/Content/selectorfiltro.css">

@{
    ViewBag.Title = "LlamadaCampeonaDuracion";
    var mod = (List<Xynthesis.Modelo.xy_costcenters>)ViewData["area"];
    var mod1 = (List<Xynthesis.Modelo.xyp_SelDetailChampCallDuration_Result>)ViewData["llamadaentrante"];
}

<div class="container">
    <br />
    <div class="text-center">
        <h2><strong>Llamada campeona por duración </strong></h2>
    </div>
    <br />
    <br />

    <div class="row">
        <div class="col-md-10">
            @using (Html.BeginForm("LlamadaCampeonaDuracion_", "ReporteLlamadaCampeonaDuracion", FormMethod.Get))
            {
                <div class="form-group form-inline">
                    @Html.TextBox("FechaInicial", null, new { @class = "form-control", @placeholder = "Fecha inicial", style = "width:110px" })
                    @Html.TextBox("FechaFinal", null, new { @class = "form-control", @placeholder = "Fecha final", style = "width:110px" })
                    <select class="selectpicker" multiple data-actions-box="true" data-live-search="true" data-live-search-placeholder="ÁREA" title="ÁREA" id="NomUsuario" name="areaId" data-size="10">
                        @foreach (var usuar in mod)
                        {
                            <option id="@usuar.Nom_CostCenter" value="@usuar.Ide_CostCenter">@usuar.Nom_CostCenter</option>
                        }
                    </select>
                    <select class="selectpicker" multiple data-actions-box="true" data-live-search="true" data-live-search-placeholder="DESTINO" title="DESTINO" id="NumEntranteId" name="numentrante" data-size="10" style="width:125px">
                        @foreach (var usuar in mod1)
                        {
                            <option id="@usuar.target" value="@usuar.target">@usuar.target</option>
                        }
                    </select>
                    @*<input type="submit" name="btnEnviar" id="enviar" class="btn btn-success" value="GENERAR" />*@
                    <button type="submit" name="btnEnviar" id="enviar" class="btn btn-success" title="GENERAR"><i class="fas fa-file-export"></i></button>
                    <div class="form-group mx-5 text-center pull-right" id="fec">
                        <label id="lblFechas" class="control-label">@ViewBag.fechaini @ViewBag.fechafin</label>
                    </div>
                </div>
            }
        </div>
        <div class="col-md-2 text-right">
            @using (Html.BeginForm("Reportes", "ReporteLlamadaCampeonaDuracion"))
            {
                <div class="form-group form-inline ">
                    <select name="opcion" class="form-control">
                        <option value="pdf">PDF</option>
                        <option value="excel">EXCEL</option>
                        <option value="word">WORD</option>
                    </select>

                    @*<input type="submit" name="btnGenerarReporte" id="GenerarReporte" value="EXPORTAR" class="btn btn-success" />*@
                    <button type="submit" name="btnGenerarReporte" id="GenerarReporte" class="btn btn-success" title="EXPORTAR"><i class="fas fa-print"></i></button>
                </div>
            }
        </div>
    </div>
    <table class="table table-condensed table-responsive table-hover">
        <tr tr style="background-color:#E1E1E1;">
            <th>
                <strong>ORIGEN</strong>
            </th>
            <th>
                <strong>ÁREA</strong>
            </th>
            <th>
                <strong>DESTINO</strong>
            </th>
            <th class="text-center">
                <strong>MINUTOS</strong>
            </th>
            <th class="text-center">
                <strong>COBERTURA</strong>
            </th>
            <th class="text-center">
                <strong>FECHA</strong>
            </th>

        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.number)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.centerc)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.target)
                </td>
                <td class="text-center">
                    @Html.DisplayFor(modelItem => item.TotalMinutos)
                </td>
                <td class="text-center">
                    @Html.DisplayFor(modelItem => item.coverage)
                </td>
                <td class="text-center">
                    @Html.DisplayFor(modelItem => item.Date)
                </td>

            </tr>
        }

    </table>
    <br />
    Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount
    @Html.PagedListPager(Model, page => Url.Action("LlamadaCampeonaDuracion", new { page, opcion = ViewBag.paraPaginacion, paraPaginacion = ViewBag.paraPaginacion }))

</div>
<script src="~/Scripts/NotacionDecimal.js"></script>