Xynthesis.Web/Controllers/ReporteProgramadoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Xynthesis.Modelo;
using CrystalDecisions.CrystalReports.Engine;
using CrystalDecisions.Shared;
using CrystalDecisions.Web;
using PagedList.Mvc;
using PagedList;
using System.IO;
using Xynthesis.Utilidades;
using Xynthesis.AccesoDatos;
using Xynthesis.Utilidades.Mensajes;
using System.Net;
using System.Configuration;

namespace Xynthesis.Web.Controllers
{
    public class ReporteProgramadoController : Controller
    {
        Utilidades.Constantes cons = new Constantes();
        AccesoDatos.ADReporteProgramado repProg = new ADReporteProgramado();
        AccesoDatos.ADUsuarios usua = new ADUsuarios();
        Utilidades.LogXynthesis log = new LogXynthesis();
        Xynthesis.Utilidades.Mensaje msg = new Mensaje();
        xynthesisEntities xyt = new xynthesisEntities();



        public ActionResult ListaRepProgramado(int? page)
        {

            if (Session["Ide_Subscriber"] == null)
            {
                return RedirectToAction("Login", "Acceso");
            }


            try
            {
                int pageSize = cons.MaxRegGrilla == null ? 8 : Convert.ToInt32(cons.MaxRegGrilla);
                int pageIndex = 1;
                pageIndex = page.HasValue ? Convert.ToInt32(page) : 1;
                return View("ListaRepProgramado", repProg.ObtenerListaRepProgramado().ToList().ToPagedList(pageIndex, pageSize));

            }
            catch (Exception ex)
            {

                log.EscribaLog("LISTA DE REPORTE PROGRAMADO", "Action:Index " + ex.Message, Session["Nom_DomainUser"].ToString());
                return RedirectToAction("Error", "Error");
            }
        }


        public ActionResult OrdenFiltro(string sortOrder, string searchString, int? page)
        {
            try
            {
                int pageSize = cons.MaxRegGrilla == null ? 8 : Convert.ToInt32(cons.MaxRegGrilla);
                int pageIndex = 1;
                pageIndex = page.HasValue ? Convert.ToInt32(page) : 1;

                ViewBag.NameSortParm = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "";
                ViewBag.DateSortParm = sortOrder == "Date" ? "date_desc" : "Date";
                var res = repProg.OrdenFiltro(sortOrder, searchString);

                var pagedList1 = res.ToPagedList(pageIndex, pageSize);
                return View("ListaRepProgramado", pagedList1);
            }
            catch (Exception ex)
            {
                log.EscribaLog("ORDEN FILTRO", "Action:OrdenFiltro " + ex.Message, Session["Nom_DomainUser"].ToString());
                return RedirectToAction("Error", "Error");
            }
        }


        
        public ActionResult RepProgramado()
        {
            ViewBag.Frecuencia = new SelectList(xyt.xy_frecuencia.ToList(), "FrecuenciaId", "NombreFrecuencia");

            if (Session["Ide_Subscriber"] == null)
            {
                return RedirectToAction("Login", "Acceso");
            }

            ViewData["confProgr"] = xyt.xy_configuracionrptprogramado.ToList();

            var lista = xyt.xy_reportes.ToList();

            return View(lista);
        }

        [HttpPost]
        public ActionResult RepProgramado(string NombreConfiguracion,string iden, string formato, string FechaInicial, string FechaFinal,  string horaEjec, string email, string copiaCorreo, string asunto, string txtMensaje, string opFrecuencia, string txtNumDia, string opDiaSemana, string txtDiaNumMes)
        {
            if(NombreConfiguracion == null)
            {
                return RedirectToAction("RepProgramado");
            }
            int IdFrecuencia = 0;
            if (opFrecuencia == "diaria")
            {
                IdFrecuencia = Convert.ToInt32(txtNumDia); //Cada IdFrecuencia dias
            }else if(opFrecuencia == "semanal")
            {
                IdFrecuencia = Convert.ToInt32(opDiaSemana); //los opDiaSemana de cada semana
            }else if(opFrecuencia == "mensual")
            {
                IdFrecuencia = Convert.ToInt32(txtDiaNumMes); //los txtDiaNumMes de cada mes
            }



            //Frecuencia
            
            if (Session["Ide_Subscriber"] == null)
            {
                return RedirectToAction("Login", "Acceso");
            }



            bool exists = (from nomb in xyt.xy_configuracionrptprogramado
                           where nomb.Nombre == NombreConfiguracion
                           select nomb).Any();

            if (exists == true)
            {
                ViewBag.Message = MensajesXynthesis.existeRegi;
                Session["mensale"] = MensajesXynthesis.existeRegi;
                Session["codigo"] = "0";
                return RedirectToAction("ListaRepProgramado");
            }

            string valor = iden;
            Char separador = '|';
            String[] letras = iden.Split(separador);
            string caracte = email.Replace(",",";");
            

            string correo = caracte.ToLower();
            string copiaCor = copiaCorreo.ToLower();

            try
            {
                for(int i = 0; i<letras.Length; i++)
                {
                    if (! letras[i].Equals(""))
                        xyt.xyp_InsRepProg(Convert.ToInt32(letras[i]), NombreConfiguracion, Convert.ToDateTime(horaEjec), formato, correo, copiaCor, asunto, txtMensaje, "", IdFrecuencia, FechaInicial, FechaFinal, opFrecuencia, IdFrecuencia);
                }
                ViewBag.Message = MensajesXynthesis.Nuevo;
                Session["mensale"] = MensajesXynthesis.Nuevo;
                Session["codigo"] = "1";
                return RedirectToAction("ListaRepProgramado");
            }
            catch (Exception error)
            {
                Session["mensale"] = MensajesXynthesis.NoProcesa;
                Session["codigo"] = "0";
                log.EscribaLog("reporte", "Action:Create " + error.Message, Session["Nom_DomainUser"].ToString());
                return RedirectToAction("Error", "Error");
            }   


        }



        public ActionResult EditarRepProg(int? id)
        {
            if (Session["Ide_Subscriber"] == null)
            {
                return RedirectToAction("Login", "Acceso");
            }

            ViewData["confProgr"] = xyt.xy_reportes.ToList();
            try
            {
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                xy_configuracionrptprogramado confrep = xyt.xy_configuracionrptprogramado.Find(id);

                ViewData["listaReportes"] = (from s in xyt.xy_configuracionreporte where s.CondiguracionId == confrep.ConfiguracionId select s).ToList();

                if (confrep == null)
                {
                    return HttpNotFound();
                }

                string fecha = Convert.ToString(confrep.HoraEjecucion.ToString("hh:mm"));

                return View(confrep);

            }
            catch (Exception ex)
            {
                log.EscribaLog("EDITAR USUARIO", "Action:EditarRepProg " + ex.Message, Session["Nom_DomainUser"].ToString());
                return RedirectToAction("Error", "Error");
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult EditarRepProg(xy_configuracionrptprogramado xy_subscriber, int ConfiguracionId, string Nombre, string iden, string horaRep, string FormatoArchivo, string EmailFrom, string Asunto, string txtMensaje)
        {
            if (Session["Ide_Subscriber"] == null)
            {
                return RedirectToAction("Login", "Acceso");
            }

            string caracte = EmailFrom.Replace(",", ";");


            string correo = caracte.ToLower();
     


            try {
                xyt.xyp_UpdRepProgra(ConfiguracionId, iden);
                xy_configuracionrptprogramado confrep = xyt.xy_configuracionrptprogramado.Find(xy_subscriber.ConfiguracionId);                

                confrep.FormatoArchivo = FormatoArchivo;
                confrep.EmailFrom = correo;
                confrep.HoraEjecucion = Convert.ToDateTime(horaRep);
                confrep.Asunto = Asunto;
                confrep.Mensaje = txtMensaje;

                repProg.EditarRepProgram(confrep);
                ViewBag.Message = MensajesXynthesis.Actualiza;
                Session["mensale"] = MensajesXynthesis.Actualiza;
                Session["codigo"] = "1";
                return RedirectToAction("ListaRepProgramado");
               

            }
            catch (Exception ex)
            {
                ViewBag.Message = MensajesXynthesis.NoProcesa;
                Session["mensale"] = MensajesXynthesis.NoProcesa;
                Session["codigo"] = "0";
                log.EscribaLog("EDITAR USUARIO", "Action:EditarRepProg " + ex.Message, Session["Nom_DomainUser"].ToString());
                return RedirectToAction("Error", "Error");
            }

        }

        public ActionResult EliminarRegistro(long? id)
        {
            if (Session["Ide_Subscriber"] == null)
            {
                return RedirectToAction("Login", "Acceso");
            }
            return PartialView("../PopupDel/EliminarRegistro");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult EliminarRegistro(int id, int? page)
        {
            msg = new Mensaje();
            msg.codigo = -1;
            if (Session["Ide_Subscriber"] == null)
            {

                return RedirectToAction("Login", "Acceso");
            }
            

            try
            {
                ViewBag.Message = "";

                int verifica = xyt.xy_configuracionrptprogramado.Where(i => i.ConfiguracionId == id).Count();
                if (verifica > 0)
                {

Xynthesis.Web/Views/ReporteProgramado/EliminarRepProgr.cshtml
@model Xynthesis.Modelo.xy_configuracionrptprogramado

@{
    ViewBag.Title = "Eliminar Sucursal";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container">
    <div class="col-md-3"></div>
    <div class="col-md-8">
        <h2><strong>Eliminar el reporte programado</strong></h2>
        <div>

    
                <div class="form-group row">                    
                    <div class="col-md-10">
                        <input type="text" class="form-control hidden" value="@Model.ConfiguracionId" disabled="disabled" />
                    </div>
                </div>

                <div class="form-group row">
                    <div class="text-right">
                        <label class="control-label col-md-2">NOMBRE</label>
                    </div>
                    <div class="col-md-10">
                        <input type="text" class="form-control" value="@Model.Nombre" disabled="disabled" />
                    </div>
                </div>
                <div class="form-group row">
                <div class="text-right">
                    <label class="control-label col-md-2">HORA</label>
                </div>
                <div class="col-md-10">
                    @{
                        var hor = Convert.ToString(Model.HoraEjecucion.ToString("HH:mm"));

                    }
                    @Html.TextBox("hora", hor, new { @class = "form-control", @type = "time", disabled = "disabled" })

                    @*<input type="text" class="form-control" value="@Model.HoraEjecucion" disabled="disabled" />*@
                </div>
                </div>

                <div class="form-group row">
                <div class="text-right">
                    <label class="control-label col-md-2">FORMATO</label>
                </div>
                <div class="col-md-10">
                    <input type="text" class="form-control" value="@Model.FormatoArchivo" disabled="disabled" />
                </div>
                </div>

                <div class="form-group row">
                <div class="text-right">
                    <label class="control-label col-md-2">EMAIL</label>
                </div>
                <div class="col-md-10">
                    <input type="text" class="form-control" value="@Model.EmailFrom" disabled="disabled" />
                </div>
                </div>

                <div class="form-group row">
                <div class="text-right">
                    <label class="control-label col-md-2">ASUNTO</label>
                </div>
                <div class="col-md-10">
                    <input type="text" class="form-control" value="@Model.Asunto" disabled="disabled" />
                </div>
                </div>

                <div class="form-group row">
                <div class="text-right">
                    <label class="control-label col-md-2">MENSAJE</label>
                </div>
                <div class="col-md-10">
                    <textarea class="form-control" value="@Model.Mensaje" disabled="disabled">@Model.Mensaje</textarea>
                </div>
            </div>            
        </div>


        <div class="row">
            <div class="col-md-2"></div>
            <div class="col-md-10 row">
                @using (Html.BeginForm())
                {
                    @Html.AntiForgeryToken()

                    <div class="form-actions no-color">
                        <input type="submit" value="Eliminar" class="btn btn-success" />
                        @Html.ActionLink("Regresar", "ListaRepProgramado", "ReporteProgramado", new { @class = "btn btn-success" })
                    </div>
                }
            </div>
        </div>



    </div>
    <div class="col-md-3"></div>
</div>

Xynthesis.Web/Views/ReporteProgramado/ListaRepProgramado.cshtml
@using PagedList.Mvc;
@model  PagedList.IPagedList<Xynthesis.Modelo.xy_configuracionrptprogramado>
<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />
<link href="~/Content/Xynthesis.css" rel="stylesheet" />
<script src="~/Scripts/NotacionDecimal.js"></script>
@{
    ViewBag.Title = "Lista de reporte programado";
}

@if (Session["mensale"] != null)
{
    if (Session["mensale"].ToString() != "")
    {
        if (Session["codigo"] != null)
        {
            if (Session["codigo"].ToString() == "1")
            {
                <script>
                    var alerta = document.getElementById("divalert");
                     alerta.style.display = "block";
                    document.getElementById("divalert").style.color = "#2D4AA0";
                    setTimeout("alerta.style.display='none'", 15000);
                </script>
            }
            else
            {
                <script>
                    var alerta = document.getElementById("divalert");
                     alerta.style.display = "block";
                     document.getElementById("divalert").style.color = "#AB0D0D";
                     setTimeout("alerta.style.display='none'", 15000);
                </script>

            }
        }
    }
}

<div class="container">
    <div class="text-center">
        <h2><strong>Lista de reporte programado</strong></h2>
    </div>
    <br />
    @using (Html.BeginForm("OrdenFiltro", "ReporteProgramado", FormMethod.Get))
    {
        <div class="row form-inline">
            <div class="col-lg-9">
                <a role="button" class="btn btn-success" onclick="location.href='@Url.Action("RepProgramado", "ReporteProgramado")'">Nueva programación</a>

            </div>
            <div class="col-lg-3 form-group">
                @Html.TextBox("SearchString", ViewBag.CurrentFilter as string, null, new { @class = "form-control", onkeypress = "return limipiarEspeciales(event)", onpaste = "return false", @placeholder = "BUSCA POR NOMBRE", @maxlengt = "50" })&nbsp;&nbsp;
                <button type="submit" class="btn btn-success "><span class="glyphicon glyphicon-search"></span></button>
            </div>

        </div>
        <br />
    }

    <table class="table table-responsive table-hover table-striped table-condensed">
        <tr style="background-color:#E1E1E1;">
            <th>
                @Html.ActionLink("NOMBRE", "OrdenFiltro", new { sortOrder = ViewBag.NameSortParm, currentFilter = ViewBag.CurrentFilter, page = 1 }, new { @class = "text-muted" })
                @if (ViewBag.NameSortParm == "name_desc")
                {
                    <span class="glyphicon glyphicon-circle-arrow-down"></span>
                }
                else
                {
                    <span class="glyphicon glyphicon-circle-arrow-up"></span>
                }
            </th>
            <th style="color:#9C9999;">@Html.Label("PERIODICIDAD")</th>
            
            <th style="color:#9C9999;" class="text-center">@Html.Label("HORA DE EJECUCIÓN")</th>
            <th style="color:#9C9999;" class="text-center">@Html.Label("FORMATO")</th>
            <th style="color:#9C9999;">
                @Html.Label("EMAIL")
            </th>

            <th style="width:10%;"></th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Nombre)
                </td>
                <td>
                    @{
                        var periodicidad = item.TipoFrecuencia.ToString().ToUpper();
                    }
                    @periodicidad
                </td>
                
                <td class="text-center">                   
                    @{
                        var hora = item.HoraEjecucion.ToString(" HH:mm:ss");
                    }
                    @hora
                </td>
                
                <td class="text-center">
                    @Html.DisplayFor(modelItem => item.FormatoArchivo)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.EmailFrom)
                </td>
                <td class="pull-right">
                    <a role="button" onclick="location.href='@Url.Action("EditarRepProg", "ReporteProgramado",new { id = item.ConfiguracionId })'"><span class="glyphicon glyphicon-pencil" style="font-size:20px;"></span></a>&nbsp;&nbsp;&nbsp;&nbsp;
                    @Html.Raw("<a data-modal='' href='/ReporteProgramado/EliminarRegistro/" + item.ConfiguracionId + "' id='" + item.ConfiguracionId + "' title='Eliminar'> <span class='glyphicon glyphicon-trash'   style='font-size:20px;'> </span> </a>")
                </td>
            </tr>
        }

    </table>
    <div>
        <br />
        Página @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) de @Model.PageCount
        @Html.PagedListPager(Model, page => Url.Action("ListaRepProgramado", new { page, sortOrder = ViewBag.CurrentSort, currentFilter = ViewBag.CurrentFilter }))
    </div>
    <div id='myModal' class='modal fade in'>
        <div class="modal-dialog">
            <div class="modal-content">
                <div id='myModalContent'></div>
            </div>
        </div>
    </div>
</div>

@section scripts
{
    @Scripts.Render("~/Scripts/respond.js")
}

Xynthesis.Web/Views/ReporteProgramado/MostrarFrecuencia.cshtml
@model IEnumerable<Xynthesis.Modelo.xy_frecuencia>

<select class="form-control" id="IdFrecuencia" name="IdFrecuencia">
    @foreach (var item in Model)
    {
        <option value="@item.FrecuenciaId">@item.NombreFrecuencia</option>
    }
</select>